// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoPUWyYqBeaZDxZTsee3gUh349ustgxTI',
    appId: '1:772109770995:android:7838fcd9426f2cd0555786',
    messagingSenderId: '772109770995',
    projectId: 'potentia-motus',
    storageBucket: 'potentia-motus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl_Nc-TUQfYZEG-ar9gw06-qw3eX0SJlY',
    appId: '1:772109770995:ios:99b5201aa9a1d41b555786',
    messagingSenderId: '772109770995',
    projectId: 'potentia-motus',
    storageBucket: 'potentia-motus.firebasestorage.app',
    androidClientId: '772109770995-jnfeg9arn554l14ov9j9gkm6iqh0b9ub.apps.googleusercontent.com',
    iosClientId: '772109770995-0ghv5eo9r9tbsu6srtv2hg7t4kcf1ne5.apps.googleusercontent.com',
    iosBundleId: 'app.budjit.budjit',
  );
}
